name = "playfairs"
compatibility_date = "2024-11-01"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"

[vars]
ENVIRONMENT = "production"

[env.production]
NODE_VERSION = "20"
NODE_ENV = "production"

[env.preview]
NODE_VERSION = "20"
NODE_ENV = "production"
